# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13


    working_directory: /go/src/github.com/salvormallow/vulnerability-collector/
    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    steps:
      - checkout
      - run:
          name: Env setup
          command: |
            mkdir $TEST_RESULTS
            go get github.com/jstemmer/go-junit-report
      - run:
          name: Run unit tests
          command: |
            go test  -v 2>&1 ./... | go-junit-report > ${TEST_RESULTS}/report.xml
      - store_test_results:
          path: /tmp/test-results
#      - run:
#          name: Build Lambdas
#          command: |
#
#          path: /go/src/github.com/salvormallow/vulnerability-collector/lambdas
  deploy:
    docker:
      - image: hashicorp/terraform
    working_directory: /go/src/github.com/salvormallow/vulnerability-collector/
    steps:
      - checkout
      - run:
          name: Env setup
          command: |
            wget https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip
            unzip terraform_0.12.7_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
            terraform --version

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build