# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13


    working_directory: /go/src/github.com/salvormallow/vulnerability-collector/
    environment: # environment variables for the build itself.
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
      BUILD_ARTIFACTS: /tmp/build_artifacts
    steps:
      - checkout
      - run:
          name: Env setup
          command: |
            mkdir $TEST_RESULTS
            go get github.com/jstemmer/go-junit-report
      - run:
          name: Run unit tests
          command: |
            go test  -v 2>&1 ./... | go-junit-report > ${TEST_RESULTS}/report.xml
      - store_test_results:
          path: /tmp/test-results
      - run:
          name: Build binaries
          command: |
            mkdir ${BUILD_ARTIFACTS}
            cd lambdas
            for d in */ ; do
                cd $d
                DNAME=basename
                go build  -o ${BUILD_ARTIFACTS}/$DNAME
                cd ..
            done
            cd ${BUILD_ARTIFACTS}
            for f in * ; do
                zip $f.zip $f
                rm $f
            done

      - persist_to_workspace:
          root: ./
          paths:
            - terraform
            - build_artifacts
#      - run:
#          name: Build Lambdas
#          command: |
#
#          path: /go/src/github.com/salvormallow/vulnerability-collector/lambdas
  deploy:
    docker:
      - image: hashicorp/terraform
    working_directory: /go/src/github.com/salvormallow/vulnerability-collector/
    steps:
      - attach_workspace:
          at: /go/src/github.com/salvormallow/vulnerability-collector/
      - run:
          name: Init terraform
          command: terraform init -backend-config="key=vulnerability-collector/prod.tfstate"
          path: /go/src/github.com/salvormallow/vulnerability-collector/terraform
      - run:
          name: Env setup
          command: |
            terraform --version
            ls
            pwd
          path: /go/src/github.com/salvormallow/vulnerability-collector/terraform
      - run:
          name: Plan terraform
          command: terraform plan out=plan.out
          path: /go/src/github.com/salvormallow/vulnerability-collector/terraform
          environment:
            TF_VAR_prefix: test21
      - run: cat plan.out
      - run:
          name: Apply terraform
          command: terraform apply -auto-approve plan.out
          path: /go/src/github.com/salvormallow/vulnerability-collector/terraform



workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build