swagger: "2.0"
info:
  title: Vulnerability collector API
  description: This API will provide access to vulnerability data and metadata collected by the vulnerability collector service.
  version: 0.0.1
host: api.hotkeycc.com
schemes:
  - https
paths:
  /healthcheck:
    get:
      summary: Returns a 200 if the service is online
      description: Hit this endpoint to detect if the service is accepting requests.
      responses:
        200:
          description: OK
